// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfQd7SlsI_X8e6y7h19VtVQpjOin2Btbk',
    appId: '1:1032237191380:web:11bcb39c54a22222d7eb41',
    messagingSenderId: '1032237191380',
    projectId: 'numou-a982e',
    authDomain: 'numou-a982e.firebaseapp.com',
    databaseURL: 'https://numou-a982e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'numou-a982e.firebasestorage.app',
    measurementId: 'G-LDDH1VWVM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWiGDKEs1LpCHH3PDd6VYgnKsjYoqTolA',
    appId: '1:1032237191380:android:47707522277f53b8d7eb41',
    messagingSenderId: '1032237191380',
    projectId: 'numou-a982e',
    databaseURL: 'https://numou-a982e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'numou-a982e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnNqRz-vh5fayfFDwoVzo0hNjru4M9bXA',
    appId: '1:1032237191380:ios:9cc23f965544411ad7eb41',
    messagingSenderId: '1032237191380',
    projectId: 'numou-a982e',
    databaseURL: 'https://numou-a982e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'numou-a982e.firebasestorage.app',
    iosClientId: '1032237191380-s11i8hv5s8feb02mci6tl8lb8jc5qhks.apps.googleusercontent.com',
    iosBundleId: 'com.example.numou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnNqRz-vh5fayfFDwoVzo0hNjru4M9bXA',
    appId: '1:1032237191380:ios:9cc23f965544411ad7eb41',
    messagingSenderId: '1032237191380',
    projectId: 'numou-a982e',
    databaseURL: 'https://numou-a982e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'numou-a982e.firebasestorage.app',
    iosClientId: '1032237191380-s11i8hv5s8feb02mci6tl8lb8jc5qhks.apps.googleusercontent.com',
    iosBundleId: 'com.example.numou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfQd7SlsI_X8e6y7h19VtVQpjOin2Btbk',
    appId: '1:1032237191380:web:f7389e8f28767a51d7eb41',
    messagingSenderId: '1032237191380',
    projectId: 'numou-a982e',
    authDomain: 'numou-a982e.firebaseapp.com',
    databaseURL: 'https://numou-a982e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'numou-a982e.firebasestorage.app',
    measurementId: 'G-G5TXSH92HM',
  );

}